### ISSUE TITLE
is structured append supported?

### ISSUE THREAD

**Issue by DanielRuf** [keriati/PQRCode#1]
would like to generate up to 16 qr codes from 1 existing file (eg a small javascript file is generated to 16 qr codes holding the sourcecode of the javascript file)

**Comment by keriati** [comment]
I am using the ZXing (http://code.google.com/p/zxing/) library at the moment, and as much i know, they don't support structured append.

**Comment by DanielRuf** [comment]
hm so there are no current solutions (as standalone jar) to generate qr codes using structured append?
Why not? QR codes could be the future 

Think about this scenario: Someone writes a book about javascript and adds some examples for download on a cd or website but these data are lost after many years (website shutdown or cd is broken) but he could add the source codes as printed qr codes using structured append - these data are always available until the paper is too old to hold the printed colors and information ...

So it would make much sense to support this ?

**Comment by keriati** [comment]
Well i don't think you need structured append for this, one qrcode can hold a lot of data (http://en.wikipedia.org/wiki/QR_code#Storage) without structured append. But if ZXing (or some other opensource java qrcode library) will support this, i will implement it.

**Comment by DanielRuf** [comment]
2 KBytes are not so much for full sourcecodes of little scripts.

Well, this would be great =)
